version: '3.7'
services:
  mongobackups:
    image: akhilrs/mongodb-cloud-backup:alpine
    container_name: 'utils.mongobackups'
    restart: always
    volumes:
      - ../db_backups:/backups
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SCHEDULE=@every 0h1m0s # https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
      - CLOUD_BACKUP=True
      - CLOUD_PROVIDER=AWS  # Azure or AWS
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - S3_SUB_FOLDER=${S3_SUB_FOLDER}
      - AWS_REGION=${AWS_REGION}
    networks:
      - backend
networks:
  backend: